### PR TITLE
zfs.sh - add * to case command

### PR DESCRIPTION
**Pull request by tschettervictor**

### CODE REVIEW

**Comment by tschettervictor** [comment]
@bmac2 @yaazkal 

If its ok with you guys, I'm going to go through each bastille script and see if anything can be streamlined or fixed or even improved somewhat. 

Wondering on your thoughts?

Most things like zfs.sh here are fine, but need some additional things like this PR.

**Comment by bmac2** [comment]
What is use case for this?
How do I test it?

**Comment by tschettervictor** [comment]
It's simply if you do "bastille zfs blabla" it should error exit.

It's to filter out all non commands.

**Comment by bmac2** [comment]
acts the same for me before and after.  So no change in what I see.  What am I doing wrong?

**Comment by tschettervictor** [comment]
My bad. It should be.

bastille zfs jail blablabla 

As opposed to the regular commands.

**Comment by bmac2** [comment]
still no changes so it acts the same with both the original zfs.sh and the new zfs.sh

**Comment by bmac2** [comment]
root@fbsd:/usr/local/share/bastille # bastille zfs jail blabla
[jail]: Not found.
root@fbsd:/usr/local/share/bastille # bastille zfs jail3 blahblah
Usage: bastille zfs TARGET [set|get|snap] [key=value|date]'
root@fbsd:/usr/local/share/bastille # mv zfs.sh new.zfs.sh
root@fbsd:/usr/local/share/bastille # cp old.zfs.sh zfs.sh
root@fbsd:/usr/local/share/bastille # bastille zfs jail3 blahblah
Usage: bastille zfs TARGET [set|get|snap] [key=value|date]'
root@fbsd:/usr/local/share/bastille #

**Comment by tschettervictor** [comment]
On mine it just doesn't do anything with the original. But with this changes the help message shows up...

**Comment by tschettervictor** [comment]
Skip this one. I think I opened it before doing the new functions. Thats probably what going on.

Let's move on to the other PRs.

**Pull request closed without merging**
