### PR TITLE
Destroy release also destroys the cached release

### PR DESCRIPTION
**Pull request by foudfou**
Clarification for #715

### CODE REVIEW

**Comment by yaazkal** [comment]
I'll keep the force flag and document it better if needed rather than change the behavior. Today storage is cheaper than networking and processing time if the user wants to bootstrap the release again.

what do you think @cedwards ?

**Comment by bmac2** [comment]
I concur we do NOT want this deleting the release.  Closing this one as will not do / works as designed.

**Comment by foudfou** [comment]
Fair enough. The first commit 62991b6778ce832c51862ec829d89a37f2a52896 was about improving the documentation though. Would you still be interested in me rebasing to merge?

**Comment by yaazkal** [comment]
@foudfou sure, improving documentation would be great, thanks.

**Comment by foudfou** [comment]
Rebased. This is ready to merge.

**Review by bmac2 — APPROVED** [review]
approved

**Comment by yaazkal** [comment]
thanks @foudfou @bmac2

**Pull request merged**
