### PR TITLE
zfssample

### PR DESCRIPTION
**Pull request by pvuchetich**
Add bastille.conf.zfssample for new install, update README

### CODE REVIEW

**Comment by pvuchetich** [comment]
This is my first pull request - I would appreciate being corrected / informed if I need to do something different.
The reasoning for this .zfssample file is that the original sample was confusing.
The original bastille.conf.sample included the annotation ## default: "${bastille_zfs_zpool}/bastille", but the default is actually "bastille".
When I used the exact string "${bastille_zfs_zpool}/bastille", it resulted in zfs filesystem creation errors.
```
original bastille.conf.sample
bastille_zfs_prefix="bastille"                                        ## default: "${bastille_zfs_zpool}/bastille"
```
The bastille.conf.zfssample uses "zroot" because that is the default zfs poolname on a FreeBSD 12.2-RELEASE installation.

The intention is that this could be copied to bastille.conf on a fresh default install of the most recent FreeBSD and just work.

**Review by hackacad — APPROVED** [review]
(1) yes,  bastille_zfs_mountpoint was already removed from Bastille.conf (it's not use anywhere in the code)
(2) yes, prefix should be `bastille` not `{bastille_prefix}/bastille`

**Comment by hackacad** [comment]
You should change bastille.conf.sample (`bastille_zfs_prefix` defaults to...)  as well

**Comment by hackacad** [comment]
I wouldn't create a .sample file for every use case.
It's just two commands. 
```
sysrc -f /usr/local/etc/bastille/bastille.conf bastille_zfs_enable=YES
sysrc -f /usr/local/etc/bastille/bastille.conf bastille_zfs_zpool=zroot
```

Maybe this could/should be added to docs.

**Review by hackacad — CHANGES_REQUESTED** [review]
Feedback: Please create a separate PR for every issue. It's three changes in one PR.

**Comment by pvuchetich** [comment]
ok - I interpreted the change as a single conceptual revision, but can work to break it up as follows, and submit multiple replacement PRs after resyncing to make sure there are no conflicts.
1. remove the .zfssample file (will not use separate file for sample per feedback)
2. correct the original .sample file (error in annotation text, not in actual variable)
3. Separate PR for README (to remove the reference to a variable no longer in use)
4. Add content to documentation with 2 line sysrc example, possibly additional descriptive text as needed.

Process question: Is it best to "Close/Reject" this PR, and submit all new ones, or to trim this one down to one change (e.g. just the README file), and submit multiple new ones?

**Comment by cedwards** [comment]
In the end, whichever is easiest for you.
There are going to be new PR either way. 😄

**Comment by hackacad** [comment]
There's way to modify the current PR, but the easiest way is to simply close it and create a new PR.

**Comment by pvuchetich** [comment]
ok. Thanks. closing and will submit new, smaller ones.

**Pull request closed without merging**
