### PR TITLE
Make parsing on jail.conf more robust

### PR DESCRIPTION
**Pull request by cqexbesd**
jail.conf has a few tricky things about it's format (such as supporting
variable expansion) so it is easiest to get jail to do the parsing for us.

The changes to `get` required changes to `set` as well as we are no longer calling grep so that became a single awk script as well.

I hope there are some good tests for this code! One thing that has changed is the stripping of quotes on output, if they were present. I think this is better than sometimes having (and makes things easier for me for an upcoming change). I didn't see anywhere that broke existing code but I'm just a beginner.

### CODE REVIEW

**Comment by cqexbesd** [comment]
I have spotted a bug so this isn't ready to be merged yet. Will push an update soon.

**Comment by cqexbesd** [comment]
OK I think its good to go now. I missed adding a new line to the config if the property wasn't already set.

**Comment by cqexbesd** [comment]
One other change in behaviour is that "not set" is now just printed and doesn't go via `warn`. Is this a problem? Let me know if you want that fixed.

**Comment by cqexbesd** [comment]
> One other change in behaviour is that "not set" is now just printed and doesn't go via `warn`. Is this a problem? Let me know if you want that fixed.

OK I realise I was just being lazy so I had fixed that now as well. Hopefully that's the last of it!

**Comment by JRGTH** [comment]
Just basic tested with/without quotes and with/without spaces, and with pipe `|` character, and working here as expected.

P.S. Letting `jail` the parsing with variable expansion seems nice to have.

Sample output [HERE](https://dpaste.org/0gF4t)

**Review by JRGTH — COMMENTED** [review]
Tested the basics and the `jail` parsing and var expansion seems to be working here as expected.
Between more testing is welcome.

**Pull request merged**
