### PR TITLE
fix for new shell check

### PR DESCRIPTION
**Pull request by tschettervictor**
Accidentally deleted #764

### CODE REVIEW

**Comment by bmac2** [comment]
what release has a patch on it. I can't find one to test with   @tschettervictor

**Comment by tschettervictor** [comment]
I believe 13.4 is on p2 already

**Comment by bmac2** [comment]
not working .  I copied your list.sh file into place ,left everything else the same.  I downloaded multiple releases trying to see a patch level and hereis what I see:



root@fbsd:/usr/local/share/bastille # bastille list release 
13.3-RELEASE
13.4-RELEASE
14.1-RELEASE
root@fbsd:/usr/local/share/bastille # bastille list release -p
13.3-RELEASE
13.4-RELEASE
14.1-RELEASE
root@fbsd:/usr/local/share/bastille # 

and i freshly downloaded all releases on a fresh FBSD install of 14.1

**Comment by tschettervictor** [comment]
```
root@webmin:~ # bastille list release -p
13.4-RELEASE
14.0-RELEASE-p11
```

Did you do `bastille update 14.0-RELEASE`

**Comment by bmac2** [comment]
works as advertised.  Merging

**Pull request merged**
