### PR TITLE
Added bootstrap checksum validation and minor fixes

### PR DESCRIPTION
**Pull request by JRGTH**
Hi cedwards, this small update will add distfiles checksum validation and minor fixes.
Regards

### CODE REVIEW

**Comment by JRGTH** [comment]
Hi, added the wanted output message if a jail depend on a base releases, also it will scan related jails too.
Regards

**Comment by JRGTH** [comment]
Hi, follow fix is for create the required jail/**root** dataset on ZFS setups.
Regards

**Comment by cedwards** [comment]
This all looks pretty good. I will merge it this weekend.

**Comment by JRGTH** [comment]
Great cedwards, thanks for such great work, there is more to come to improve this overall work, :)

**Pull request merged**
