### PR TITLE
Fix a couple of bugs in the "mount" command

### PR DESCRIPTION
**Pull request by markjdb**

### CODE REVIEW

**Review by chriswells0 — APPROVED** [review]
Ship it!

**Comment by JRGTH** [comment]
Hi, I've fixed the mount command in one of my previously stacked PR's: https://github.com/BastilleBSD/bastille/pull/337/commits/2c87c58a5b71f6753b79810f7a34144694e2b54f

I guess this solution will indeed works as intended as well, I considering to re-parse every of my pending PRs and close my own duplicates to avoid further conflicts.

Regards

**Comment by chriswells0** [comment]
Yeah, I saw yours after I saw this one. I think there are actually 3 fixes for this issue right now. :(

**Comment by JRGTH** [comment]
Right, sometimes PR's stack and duplicates happens over time, but also we understand Christer is lately busy with traveling plus meetings around, I just will improve/test locally until he freed up some time for reviewing PR's and minimize clutter/stacked PR's. ;)

**Comment by markjdb** [comment]
Should I just close this PR then, given that there are other patches for the same bugs?

**Comment by JRGTH** [comment]
Hi, please keep it for now, since I'm considering closing mines since I've made more than the PR's stacks that I normally do, so I can carefully revise all of them and make just one maintenance commit to make it more easy for Christer to review.

Regards

**Comment by cedwards** [comment]
Thank you for your work with this. My fault for not getting to this sooner. The issue has now been fixed in a separate pull request; closing.

**Pull request closed without merging**
