### PR TITLE
Allow using template in custom directory

### PR DESCRIPTION
**Pull request by tschettervictor**
This PR will allow users to specify any template directory to use with Bastille.
If the template is not found in the template directory, it will check the current directory and try to determine if a Bastillefile is present. If not, it will exit as normal.

### CODE REVIEW

**Comment by michael-o** [comment]
What is actually the usecase here?

**Comment by tschettervictor** [comment]
Running a temple in current directory.

Right now one can only run templates when the are in two locations. The templates directory, or one directory lower than PWD.

Say I have a template I'm working on inside a folder called "guacamole" that I want to run. I would first have to back up one directory and then have to run the template command with "directory/guacamole"

This PR simply allows me to run "guacamole" as the template arg.

**Comment by michael-o** [comment]
I see, but running nested local templates would still not be possible since you need to use a slash..

**Comment by tschettervictor** [comment]
It is possible currently. And would still be possible with this PR. If you look at the case command, there are only two options, the template directory and the current directory/other.

This PR simply adds an additional case block allowing for any other input. It will check if that input is a directory, then if it is, check if there is a Bastillefile inside. If not, exit.

**Comment by bmac2** [comment]
tested the  following:
1. standard location templates - passed
2. put a template in my home directory and applied it - passed
3. templates in /usr/local/bastille/templates/bastillebsd-templates - passed

**Comment by yaazkal** [comment]
This was reverted in https://github.com/BastilleBSD/bastille/pull/779 since it broke the `template` subcommand.

@tschettervictor feel free to open a new PR.

**Comment by tschettervictor** [comment]
No issue. After careful consideration, it's probably best to leave it as is.

Templates should follow the structure of project/template anyway in my opinion.

While it would be nice to still do it as I wanted, it's not an important addition.

Thanks for pointing that out.

**Comment by tschettervictor** [comment]
Oops I just noticed I was actually missing a ;; at the end.

I'll open a new PR for you to test...

**Pull request merged**
