### PR TITLE
Add autocomplete jail name function

### PR DESCRIPTION
**Pull request by tschettervictor**
This will allow a user to simple begin typing a jail name. If bastille finds more than one jail starting with what is typed, it will error. If it only find one jail, it will set that jail as the $TARGET

```
root@webmin:~ # bastille list all
 JID   State  IP Address  Published Ports  Hostname  Release       Path
 teer  Up     10.0.0.3    -                teer      14.0-RELEASE  /usr/local/bastille/jails/teer/root
 test  Up     10.0.0.1    -                test      14.0-RELEASE  /usr/local/bastille/jails/test/root
 tesw  Up     10.0.0.2    -                tesw      14.0-RELEASE  /usr/local/bastille/jails/tesw/root
root@webmin:~ # bastille console te
Multiple jails found for te:
teer test tesw
root@webmin:~ # bastille cmd tes
Multiple jails found for tes:
test tesw
root@webmin:~ # bastille console tee
[teer]:
root@teer:~ #
```

### CODE REVIEW

**Comment by tschettervictor** [comment]
@yaazkal Do you think this is a necessary addition? It is not strictly necessary, but it is a decent enhancement. 

A few things i noticed is that some commands are not registered with this function, namely 

```
bootstrap|create|destroy|export|import|list|rdr|restart|setup|start|update|upgrade|verify)
    # Nothing "extra" to do for these commands. -- cwells
    ;;
```
This function would have to be called in their own CMD file.

**Comment by tschettervictor** [comment]
I've now added the function to all necessary CMD files.

**Comment by michael-o** [comment]
Why not add to bash completions?

**Comment by tschettervictor** [comment]
Using tab will not work. If you have any type of directory in the root (or wherever you run bastille command from) it will auto complete directories and files in PWD.

I think it better to use the function as-is.

**Comment by pepe82sh** [comment]
@tschettervictor funny this is very recent. I couldn't find any completion scripts for zsh (or bash) to have proper Bastille completion support in the shell. That'd include suggestions for subcommands, options and jails. Is this by any chance planned, or if it isn't, would adding completions for zsh or bash be accepted as a PR?

**Comment by tschettervictor** [comment]
Closed in favor of #758 which improves handling of this function.

**Pull request closed without merging**
